export default {
  user: null,
  manageAccountVisible: false,
  loginError: null,
  loginLoading: false,
  registerError: null,
  registerLoading: false,
  logoutLoading: false,
  logoutError: null,
  forgotLoading: false,
  forgotError: null,
  resetError: null,
  resetLoading: false,
  meLoading: false,
  meError: null,
  saveMeLoading: false,
  saveMeError: null,
  sentResetLink: null,
  resetStatus: null,
  setSiteLocaleSuccess: null,
  setSiteLocaleLoading: false,
  setSiteLocaleError: null,
  askMailVerificationNotificationLoading: false,
  askMailVerificationNotificationError: null
}
