#debug = true
#acmeLogging=true

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
    [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

[retry]

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "yourzenoffice.com"
  watch = true
  exposedbydefault = false

[acme]
  email = "a.prevot@thecodingmachine.com"
  storage = "acme.json"
  entryPoint = "https"
  onHostRule = true

[acme.tlsChallenge]

[web]  # Port for the status page
address = ":8080"
